// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjmiIX8H2ty0bgCeetCuJpx51VlmZgW7g',
    appId: '1:266788837318:web:5685af3905de9ca25b84c7',
    messagingSenderId: '266788837318',
    projectId: 'upwork-df50e',
    authDomain: 'upwork-df50e.firebaseapp.com',
    storageBucket: 'upwork-df50e.appspot.com',
    measurementId: 'G-DK2EK7FQF1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDLw21jLWMDZW44m33jYKd8UEq5A-gHE0',
    appId: '1:266788837318:android:517817b8bd470e385b84c7',
    messagingSenderId: '266788837318',
    projectId: 'upwork-df50e',
    storageBucket: 'upwork-df50e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAK_eIPSWoVFDZBQelcFkame4PPaMnXmY8',
    appId: '1:266788837318:ios:9419d5efaaef633a5b84c7',
    messagingSenderId: '266788837318',
    projectId: 'upwork-df50e',
    storageBucket: 'upwork-df50e.appspot.com',
    iosClientId: '266788837318-qt2ijc1ggaf8iibob9vgcj1c2jtrf1df.apps.googleusercontent.com',
    iosBundleId: 'com.prasisai.royal',
  );
}
